### PR TITLE
Gtk4 port

### PR DESCRIPTION
**Pull request by jwahlstrand**
Straightforward port to use Gtk4

### CODE REVIEW

**Review by jonathanBieler — APPROVED** [review]
Thanks, looks good. I should update the CI...

**Comment by jwahlstrand** [comment]
Thanks!

**Comment by jonathanBieler** [comment]
I'll update the CI and make new release.

**Comment by jwahlstrand** [comment]
Thanks, I'd also be happy to update the CI, I'd just copy what's in Gtk4.

**Comment by jonathanBieler** [comment]
Would be nice if you could have a look yes, I've copied a default file but it seems you need Gtk4 specific stuff.

**Pull request merged**
